### ISSUE TITLE
ASSIGNMENT 1A

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-GROUP-C-A211/WEEK-4#1]
### **INSTRUCTION**
You are required to calculate the total price that need to be paid by a customer in C_MARTS shopping complex. The program should ask how many items that the customer buys (maximum number of items is 3). Based on the number of items, the program will ask the quantity and price of each item. Each time the quantity and price are entered, they must be multiplied and totalled up. Then, the program should calculate the discount obtained by the customer based on the total price. If the customer buys more than RM100, he/she is entitled for 20% discount, whereas, if the total price is less than RM100 the customer is only entitled for 10% discount. Finally, the program should display the total price before discount, discount received and the amount that need to be paid. 

**Example of sample running (underlined are the input):**
![image](https://user-images.githubusercontent.com/61673158/140629005-6af36f07-d719-44c0-97b5-82dd08088fde.png)

### **SUBMISSION**
1. Complete Code and Comment for each line of code
2. Sample Output
3. Due Date: 11.15 AM (**TODAY** - 7 November 2021)

**Comment by TOHVINPING286681** [comment]
https://github.com/STIA-1113-GROUP-C-Toh-Vin-Ping/WEEK4-Assignment-1A.git

**Comment by Daniel-Fikrey-287148** [comment]
https://github.com/STIA-1113-GRP-C/WEEK-5.git

**Comment by WANRUIYIN-287456** [comment]
https://github.com/STIA1113-GROUP-C-WAN-RUI-YIN/WEEK-5.git

**Comment by TANGUANXUN287471** [comment]
https://github.com/STIA1113-GROUP-C-TAN-GUAN-XUN/WEEK-4-ASSIGNMENT.git

**Comment by ChoongQianYu-286623** [comment]
https://github.com/STIA-1113-GROUP-C-CHOONG-QIAN-YU/WEEK-4.git

**Comment by faraayeesha286941** [comment]
https://github.com/STIA-1113-GROUP-C-FARA-AYEESHA/WEEK-4.git

**Comment by KorJunXiang** [comment]
https://github.com/KorJunXiang/WEEK-5.git

**Comment by 270659teyengzin** [comment]
https://github.com/STIA-1113-GROUP-C-ZIN/Assignment1.git

**Comment by AfiqImran-286997** [comment]
https://github.com/STIA-1113-GROUP-C-AFIQ-IMRAN/Assigment.git

**Comment by Laila1911** [comment]
https://github.com/STIA-1113-GROUP-C-LAILA/WEEK-4-ASSIGNMENT.git

**Comment by NikHanis286961** [comment]
https://github.com/STIA-1113-GROUP-C-Nik-Hanis/WEEK5-Assigntment1A.git

**Comment by Aimeldaniel** [comment]
https://github.com/STIA-1113-GROUP-C-AIMEL/WEEK4-ASSIGNMENT.git

**Comment by ANGKAIZI286043** [comment]
https://github.com/STIA1113-GROUP-C-ANGKAIZI/WEEK4.git

**Comment by NorAisyah286982** [comment]
https://github.com/STIA-1113-GROUP-C-Nor-Aisyah/WEEK4.git

**Comment by JunHan016** [comment]
https://github.com/STIA1113-GROUP-C/HO-JUN-HAN-WEEK-4.git

**Comment by TANGWEICHIANG** [comment]
https://github.com/STIA-1113-GROUP-C-JOHNNY-TANG/WEEK-4-ASSIGNMENT-1A.git

**Comment by azyyatiadlin** [comment]
https://github.com/STIA-1113-GROUP-C-Azyyati-Adlin/WEEK4-ASSIGNMENT1A.git

**Comment by nuraisyah01** [comment]
https://github.com/STIA-1113-GROUP-C-NURAISYAH/WEEK-4-ASSIGNMENT.git

**Comment by Song-Zhuangqing** [comment]
https://github.com/STIA1113-GROUP-C-SongZhuangqing/WEEK4-ASSIGNMENT1.git

**Comment by HOWAIKIAT287156** [comment]
https://github.com/STIA-1113-GROUP-C-HO-WAI-KIAT/WEEK-4-ASSIGNMENT-1.git

**Comment by ChooKuaiFern277673** [comment]
https://github.com/ChooKuaiFern277673/ASSIGNMENT-1A.git

**Comment by IntanSyamimi286735** [comment]
https://github.com/STIA1113-GROUP-C-IntanSyamimi/WEEK4.git

**Comment by Haikal283950** [comment]
https://github.com/STIA1113-GROUP-C-HAIKAL/WEEK-4-ASSIGNMENT1.git

**Comment by RayyanKamal28462** [comment]
https://github.com/RayyanKamal28462/week4-assignment.git

**Comment by GohKoonLoong** [comment]
https://github.com/GohKoonLoong/WEEK-4.git

**Comment by LimHuiQi** [comment]
https://github.com/STIA-1113-GROUP-C-LIMHUIQI/WEEK4-ASSIGNMENT.git

**Comment by Aimeldaniel** [comment]
https://github.com/STIA-1113-GROUP-C-AIMEL/WEEK4-ASSIGNMENT1.git

**Comment by aainulamirahh** [comment]
https://github.com/STIA-1113-GROUP-C-Ainul-Amirah/WEE4-assignment.git

**Comment by AnisShafiqah** [comment]
https://github.com/STIA1113-GROUP-C-ANIS-SHAFIQAH/WEEK4-ASSIGNMENT1A.git

**Comment by AyshaSofea18** [comment]
https://github.com/STIA-1113-GROUP-C-Wan-Aysha-Sofea/WEEK-4-ASSIGNMENT.git

**Comment by NurfarahWahida1504** [comment]
https://github.com/STIA-1113-GROUP-C/assignment.git

**Comment by Seraafiqah** [comment]
https://github.com/Seraafiqah/Assigment-week4.git

**Comment by AQILNAJJAH** [comment]
https://github.com/STIA1113GROUP-C-PROGRAMMING-1/WEEK5.git

**Comment by zafirahnuraina** [comment]
https://github.com/STIA-1113-GROUP-C-ZAFIRAH/WEEK-4-ASSINGMENT-1A.git

**Comment by YapJiaJun287652** [comment]
https://github.com/YapJiaJun287652/ASSIGNMENT1.git

**Comment by NurAlyaBintiMohdIzazi** [comment]
https://github.com/STIA1113-GROUP-C-AlyaIzazi/WEEK4-ASSIGNMENT1A.git
