### ISSUE TITLE
ASSIGNMENT 1B

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-GROUP-C-A211/WEEK-4#2]
### **INSTRUCTION**
Say your brother wants to buy a used car for $5,000 and has only $2,000 for the down payment. 
He hits you up for a loan for the remaining $3,000. 
If the length of the loan is five years and he’s paying you simple interest of 3.5 percent per month to borrow the additional $3,000, 
Calculate the sum of interest, monthly payment and total of payment.

### Output:
Enter yearly interest rate, for example 3.5: 3.5
Enter number of years as an integer, for example 5: 5
Enter loan amount, for example 3000.00: 3000
The monthly payment is $105.0
The total payment is $6300.0

### **SUBMISSION**
1. Complete code and Comment for each line of code
2. Sample Output
3. Due date: 12.15 PM (**TODAY**-7 November 2021)

**Comment by STIA1113-GROUP-C-SongZhuangqing** [comment]
https://github.com/STIA1113-GROUP-C-SongZhuangqing/WEEK4-ASSIGNMENT1.git

**Comment by KorJunXiang** [comment]
https://github.com/KorJunXiang/WEEK-5.git

**Comment by TOHVINPING286681** [comment]
https://github.com/STIA-1113-GROUP-C-Toh-Vin-Ping/Week4-Assignment-1B.git

**Comment by TANGUANXUN287471** [comment]
https://github.com/STIA1113-GROUP-C-TAN-GUAN-XUN/WEEK-4-ASSIGNMENT.git

**Comment by WANRUIYIN-287456** [comment]
https://github.com/STIA1113-GROUP-C-WAN-RUI-YIN/WEEK-5.git

**Comment by AfiqImran-286997** [comment]
https://github.com/STIA-1113-GROUP-C-AFIQ-IMRAN/AssigmentB1.git

**Comment by faraayeesha286941** [comment]
https://github.com/STIA-1113-GROUP-C-FARA-AYEESHA/WEEK-4.git

**Comment by TANGWEICHIANG** [comment]
https://github.com/STIA-1113-GROUP-C-JOHNNY-TANG/WEEK-4-ASSIGNMENT-1B.git

**Comment by HOWAIKIAT287156** [comment]
https://github.com/STIA-1113-GROUP-C-HO-WAI-KIAT/WEEK-4-ASSIGNMENT-1B.git

**Comment by ChoongQianYu-286623** [comment]
https://github.com/STIA-1113-GROUP-C-CHOONG-QIAN-YU/WEEK-4.git

**Comment by zafirahnuraina** [comment]
https://github.com/STIA-1113-GROUP-C-ZAFIRAH/WEEK4-ASSIGNMENT-1B.git

**Comment by AnisShafiqah** [comment]
https://github.com/STIA1113-GROUP-C-ANIS-SHAFIQAH/WEEK4-ASSIGNMENT1B.git

**Comment by NikHanis286961** [comment]
https://github.com/STIA-1113-GROUP-C-Nik-Hanis/WEEK5-Assigntment1.git

**Comment by LimHuiQi** [comment]
https://github.com/STIA-1113-GROUP-C-LIMHUIQI/WEEK4-ASSIGNMENT.git

**Comment by 270659teyengzin** [comment]
https://github.com/STIA-1113-GROUP-C-ZIN/Assignment1B.git

**Comment by Laila1911** [comment]
https://github.com/STIA-1113-GROUP-C-LAILA/WEEK-4-ASSIGNMENT.git

**Comment by Haikal283950** [comment]
https://github.com/STIA1113-GROUP-C-HAIKAL/WEEK-4-ASSIGNMENT1.git

**Comment by IntanSyamimi286735** [comment]
https://github.com/STIA1113-GROUP-C-IntanSyamimi/WEEK4-ASSIGNMENT2.git

**Comment by ANGKAIZI286043** [comment]
https://github.com/STIA1113-GROUP-C-ANGKAIZI/WEEK4.git

**Comment by NorAisyah286982** [comment]
https://github.com/STIA-1113-GROUP-C-Nor-Aisyah/WEEK4.git

**Comment by Daniel-Fikrey-287148** [comment]
https://github.com/STIA-1113-GRP-C/WEEK-5.git

**Comment by Aimeldaniel** [comment]
https://github.com/STIA-1113-GROUP-C-AIMEL/WEEK4-ASSIGNMENT.git

**Comment by NurfarahWahida1504** [comment]
https://github.com/STIA-1113-GROUP-C/assignment.git

**Comment by JunHan016** [comment]
https://github.com/STIA1113-GROUP-C/HO-JUN-HAN-WEEK4-1B.git

**Comment by GohKoonLoong** [comment]
https://github.com/GohKoonLoong/WEEK-4.git

**Comment by AyshaSofea18** [comment]
https://github.com/STIA-1113-GROUP-C-Wan-Aysha-Sofea/WEEK-4-ASSIGNMENT.git

**Comment by nuraisyah01** [comment]
https://github.com/STIA-1113-GROUP-C-NURAISYAH/WEEK-4-ASSIGNMENT.git

**Comment by aainulamirahh** [comment]
https://github.com/STIA-1113-GROUP-C-Ainul-Amirah/WEE4-assignment.git

**Comment by Seraafiqah** [comment]
https://github.com/Seraafiqah/Assigment-week4.git

**Comment by AQILNAJJAH** [comment]
https://github.com/STIA1113GROUP-C-PROGRAMMING-1/WEEK5.git

**Comment by RayyanKamal28462** [comment]
https://github.com/RayyanKamal28462/week4-assignment.git

**Comment by Yasriroslan** [comment]
https://github.com/STIA1113-GROUP-C-A211/WEEK-4/issues/2

**Comment by Yasriroslan** [comment]
https://github.com/Yasriroslan/WWEK-4-ASSIGNMENT.git

**Comment by NurAlyaBintiMohdIzazi** [comment]
https://github.com/STIA1113-GROUP-C-AlyaIzazi/WEEK4-ASSIGNMENT1B.git

**Comment by ChooKuaiFern277673** [comment]
https://github.com/ChooKuaiFern277673/ASSIGNMENT1B.git

**Comment by azyyatiadlin** [comment]
https://github.com/STIA-1113-GROUP-C-Azyyati-Adlin/WEEK4-ASSIGNMENT1B.git
